name: DEV - Build
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  APP_NAME: ps-tutorial-frontend
  CONTAINER_REPOSITORY: "acrpstutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"
jobs:
  unittest:
    name: UnitTest
      runs-on: ubuntu-latest
      environment: dev
      steps:
      steps:
      - name: Checkout code
        uses: actions/checkout@v2